// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    Alpha: typeof import('./src/components/color-picker/alpha.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    Checkerboard: typeof import('./src/components/checkerboard.vue')['default']
    Container: typeof import('./src/components/container.vue')['default']
    FixedWidgets: typeof import('./src/components/fixed-widgets.vue')['default']
    Hue: typeof import('./src/components/color-picker/hue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Saturation: typeof import('./src/components/color-picker/saturation.vue')['default']
    VueAce: typeof import('./src/components/VueAce.vue')['default']
    VueCodemirror: typeof import('./src/components/vue-codemirror.vue')['default']
  }
}

export {}
