export default {
  login: () => import('@/views/login/index.vue'),
  imgHosting: () => import('@/views/common/imgHosting.vue'),
  uuid: () => import('@/views/program/uuid.vue'),
  mtqLoans: () => import('@/views/money/mtqLoans.vue'),
  timeCompute: () => import('@/views/program/timeCompute.vue'),
  colorTransform: () => import('@/views/program/colorTransform.vue'),
  jsonEditor: () => import('@/views/program/jsonEditor.vue'),
  settings: () => import('@/views/settings/index.vue'),
  whatAnimeIsThis: () => import('@/views/others/whatAnimeIsThis.vue'),
  bilibiliBv2av: () => import('@/views/others/bilibiliBv2av.vue'),
  oreooo: () => import('@/views/others/oreooo/index.vue'),
  2048: () => import('@/views/games/2048/index.vue'),
  urlEncode: () => import('@/views/program/urlEncode.vue'),
  tetris: () => import('@/views/games/tetris/index.vue'),
  viewSourceCode: () => import('@/views/program/viewSourceCode.vue'),
  cssFormatter: () => import('@/views/program/cssFormatter.vue'),
  geoJson: () => import('@/views/gis/geoJson.vue'),
  latLng: () => import('@/views/gis/latLng.vue'),
  tinyEditor: () => import('@/views/program/tinyEditor.vue'),
  idChinese: () => import('@/views/others/idChinese.vue'),
  cesiumDemo: () => import('@/views/gis/cesiumDemo/cesiumDemo.vue'),
  screenRecord: () => import('@/views/others/screenRecord.vue'),
  anyRule: () => import('@/views/program/anyRule.vue'),
  linuxCommand: () => import('@/views/program/linuxCommand.vue'),
  watermark: () => import('@/views/image/watermark.vue'),
  userAgent: () => import('@/views/program/userAgent.vue')
}
